[package]
name = "profiles"
version = "0.0.1"
edition = "2018"

[lib]
name = "profiles"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
hdk_crud = "0.0.103"
hdk = "0.0.103"
# hdk_crud = { git = "https://github.com/lightningrodlabs/hdk_crud.git", branch = "test-fork" }
# hdk = { git = "https://github.com/holochain/holochain.git", branch = "Connoropolous-patch-2" }
paste = "*"
serde = "*"
thiserror = "1"