---
environment_path: databases # note this is relative to the path from which `holochain` gets run, not where this file sits
use_dangerous_test_keystore: false
signing_service_uri: ~
encryption_service_uri: ~
decryption_service_uri: ~
dpki: ~
keystore_path: ~
passphrase_service: ~
admin_interfaces:
  - driver:
      type: websocket
      port: 1234 # must match config-admin-ws value
network: ~
