name: Release

# on:
#   push:
#     tags:
#       - v[0-9]+.*

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # create-release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: taiki-e/create-gh-release-action@v1
  #       env:
  #         # (required)
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-latest
          # - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # - uses: taiki-e/upload-rust-binary-action@v1
      #   with:
      #     # (required)
      #     bin: acorn
      #   env:
      #     # (required)
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        # if: ${{ runner.os == 'Linux' }}
        # run: npm run install-deps
        run: npm install && npm run web-install && npm run electron-install && npm run electron-tsc
      # - name: Install Sqlcipher MacOs
        # if: ${{ runner.os == 'macOs' }}
        # run: |
          # brew install sqlcipher
          # brew install libsodium
      - name: build acorn
        #         env:
        #           SQLCIPHER_STATIC: 1
        run: |
          npm run build
      - name: upload binary (ubuntu only)
        if: ${{ runner.os == 'Linux' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # cp bin/lair-keystore lair-keystore-x86_64-unknown-linux-gnu
          gh release upload "test-release" "electron/out/Acorn-0.5.2-alpha.AppImage" --clobber
      - name: upload binary (macos only)
        if: ${{ runner.os == 'macOs' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # cp bin/lair-keystore lair-keystore-x86_64-apple-darwin
          gh release upload "test-release" "electron/out/Acorn-0.5.2-alpha.dmg" --clobber
      # - name: upload binary (Windows only)
      #   if: ${{ runner.os == 'Windows' }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     Copy-Item bin/lair-keystore.exe -Destination lair-keystore-x86_64-pc-windows-msvc.exe
      #     gh release upload "test-release" "lair-keystore-x86_64-pc-windows-msvc.exe" --clobber
